[clinic]
name = "EASY MY CARE CLINIC"
address = "584,SUNVIEW APARTMENT,DDA FLATS,POCKET 4,SECTOR9"
phone = "+91 8448522336"
email = "shivesh@easymycareclinic.com"
registration = "DMC/20075"

[doctor]
name = "Dr. Shivesh kumar"
qualification = "MD PG dip cardiology"
registration_no = "DMC/20075"
specialty = "Physician"
